### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dacaito** [jawebada/libmbb#5]
Hi,

I'm looking at the HSM implementation and it looks really nice, kudos on that!

I have a doubt, the following line of code confused me:
https://github.com/jawebada/libmbb/blob/6dd52d73a8e3393004f0a44b832d81d72b3f16f0/mbb/hsm.c#L202

Does this mean that an event in a sub-state is sent to the sub-state and parent-state?
My understanding is that if the sub-state handles the event, then the parent will not receive it. Otherwise, if the sub-state doesn't handle the event, then it will be issued to the parent-state.

Am I getting something wrong?

Thanks a lot!

**Comment by jawebada** [comment]
Hi,

thanks for your interest in this library.

You are right, the implementation is *not in line with the UML spec* in this regard and this should probably be documented. From my personal experience, however, this is often what you actually need. Kind of a Liskov substitution principle for hierarchical state machines. When your state machine is in a substate it is also in the parent state and you want the parent's internal transition action to happen.

When we used / developed a state machine framework which followed the UML spec more strictly, we ended up with lots of compound actions and boolean combinations of guards. The big pro of such a state machine framework is that your state machine structure can be verified and its behavior is well defined. *libmbb* is much more flexible, but, as we know, with great power comes great responsibility.

**Comment by dacaito** [comment]
Thanks a lot for your detailed answer!

It's a valid point, I'll try to think if I can solve my problem with this condition. It is as if instead of substates (OR) they are AND substates, and you're simultaneously in all of them. 

I'll also, for the sake of it, think if there's an elegant way to convert it to traditional OR HSM. First thing that comes to mind is returning NULL when event is not handled and pass it to parent, otherwise a valid state.  However, this would render the deferred feature useless.

**Comment by jawebada** [comment]
Since your question has been answered, I am closing this issue.
